{"timestamp":"2025-08-08T02:41:39.295752","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-08T02:41:39.296619","level":"info","event":"Filling up the DagBag from /home/cnguyen/myrepos/dbt-postgres-airflow/airflow/dags/dbt-orchesstrator.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-08T02:41:39.416518Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:39.416770Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:39.416955Z","level":"info","event":"Current task name:ingest_weather_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:39.417050Z","level":"info","event":"Dag name:dbt_orchestrator","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:39.420210","level":"info","event":"Fetching data from WeatherStack API","logger":"helper_function"}
{"timestamp":"2025-08-08T02:41:40.188201","level":"error","event":"APT request failed: 400 Client Error: Bad Request for url: https://api.weatherstack.com/current?access_key=9781a0714b015931f11061873fb8ce78&query=London;Singapur;Shanghai;New%20York;Tokyo;Berlin;Hanoi;Ho%20Chi%20Minh%20City;Paris;Moscow","logger":"helper_function","error_detail":[{"exc_type":"HTTPError","exc_value":"400 Client Error: Bad Request for url: https://api.weatherstack.com/current?access_key=9781a0714b015931f11061873fb8ce78&query=London;Singapur;Shanghai;New%20York;Tokyo;Berlin;Hanoi;Ho%20Chi%20Minh%20City;Paris;Moscow","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":17,"name":"fetch_data_from_api"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/requests/models.py","lineno":1026,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-08T02:41:40.188666","level":"error","event":"An error occurred: 400 Client Error: Bad Request for url: https://api.weatherstack.com/current?access_key=9781a0714b015931f11061873fb8ce78&query=London;Singapur;Shanghai;New%20York;Tokyo;Berlin;Hanoi;Ho%20Chi%20Minh%20City;Paris;Moscow","logger":"helper_function","error_detail":[{"exc_type":"HTTPError","exc_value":"400 Client Error: Bad Request for url: https://api.weatherstack.com/current?access_key=9781a0714b015931f11061873fb8ce78&query=London;Singapur;Shanghai;New%20York;Tokyo;Berlin;Hanoi;Ho%20Chi%20Minh%20City;Paris;Moscow","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":90,"name":"main"},{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":17,"name":"fetch_data_from_api"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/requests/models.py","lineno":1026,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-08T02:41:40.189182","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"UnboundLocalError","exc_value":"local variable 'conn' referenced before assignment","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/cnguyen/.pyenv/versions/3.10.4/envs/demo_airflow/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/cnguyen/myrepos/dbt-postgres-airflow/airflow/utilities/helper_function.py","lineno":97,"name":"main"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-08T02:41:40.190646Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:40.191131Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:40.191261Z","level":"info","event":"Task:<Task(PythonOperator): ingest_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-08T02:41:40.191336Z","level":"info","event":"Failure caused by local variable 'conn' referenced before assignment","chan":"stdout","logger":"task"}
